/* tables */
table.tablesorter {
	width: 100%;
}
table.tablesorter thead tr th, table.tablesorter tfoot tr th {
	background-color: #eeeeee;
	border: 1px solid #FFF;
	font-size: 14px;
	padding: 4px;
}
table.tablesorter thead tr .tablesorter-header {
	background-image: url('data:image/gif;base64,R0lGODlhFQAJAIAAACMtMP///yH5BAEAAAEALAAAAAAVAAkAAAIXjI+AywnaYnhUMoqt3gZXPmVg94yJVQAAOw==');
	background-repeat: no-repeat;
	background-position: center right;
	cursor: pointer;
	height: 24px;
}
.tablesorter-header-inner {
	overflow: hidden;
	text-overflow: ellipsis;
	white-space: nowrap;
}
table.tablesorter tbody td {
	color: #000;
	padding: 4px 6px;
	background-color: #FFF;
	vertical-align: middle;
	height: 44px;
	font-size: 16px;
}
table.tablesorter tbody tr:nth-child(odd) td {
	background-color:#ecf9ff;
}
table.tablesorter thead tr .tablesorter-headerAsc {
	background-image: url('data:image/gif;base64,R0lGODlhFQAEAIAAACMtMP///yH5BAEAAAEALAAAAAAVAAQAAAINjB+gC+jP2ptn0WskLQA7');
	background-repeat: no-repeat;
	background-position: center right;
}
table.tablesorter thead tr .tablesorter-headerDesc {
	background-image: url('data:image/gif;base64,R0lGODlhFQAEAIAAACMtMP///yH5BAEAAAEALAAAAAAVAAQAAAINjI8Bya2wnINUMopZAQA7');
	background-repeat: no-repeat;
	background-position: center right;
}
table.tablesorter thead tr .tablesorter-headerDesc, table.tablesorter thead tr .tablesorter-headerAsc {
background-color: #3abfea;
}
