.no-close .ui-dialog-titlebar-close {
  display: none 
}

.ui-dialog .ui-dialog-buttonpane {
  text-align: right;
}
.ui-dialog .ui-dialog-titlebar {
  
}
.ui-dialog  {
  padding: 20px;
}
.bPageBlock .detailList .data2Col, .bPageBlock .labelCol {
  text-align: left;
  width:auto;
}
.ui-dialog .title {
  font-size: 1em;
  font-family: Arial,Helvetica,sans-serif;
  font-weight: bold;
  color: #27282E;
  /*margin-bottom: 30px;*/
  display: block;
}
body .bDetailBlock.bPageBlock {
  margin-bottom: 0;
}
.wait, .wait * {
  cursor: wait;
}
html.wait {
  height:100%;
}